name: reporting
channels:
  - conda-forge
dependencies:
  - dash=2.3.1
  - dash-bootstrap-components
  - matplotlib=3.5.1
  - scipy=1.8.0
  - numpy=1.22.3
  - pandas=1.4.2
  - plotly=5.7.0
  - seaborn=0.11.2
  - tqdm=4.64.0
  - urllib3=1.26.9
  - pip=22.0.4
  - requests=2.27.1
  - pip:
    - pyarrow==7.0.0
