openapi: 3.0.0
info:
  version: "0.0.0"
  title: Traceability Discovery API
  license:
    name: W3C Software and Document License
    url: http://www.w3.org/Consortium/Legal/copyright-software.
  contact:
    name: GitHub Source Code
    url: https://github.com/w3c-ccg/traceability-interop
tags:
  - name: Identifiers
    description: APIs for Decentralized Identifiers
paths:
  /.well-known/did-configuration.json:
    get:
      tags:
        - Identifiers
      summary: Get Domain Linked Decentralized Identifiers
      operationId: getDidConfiguration
      description: Gets the well known did configuration for the api.
      responses:
        "200":
          description: Linked Identifiers
        "400":
          description: Client Error
        "500":
          description: Server Error
