name: Workflow Matrix Reporter

on: ['push']

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: 'Alice'
          - name: 'Bob'
          - name: 'Eve'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Echo
        env:
          name: ${{matrix.name}}
        run: |
          date >> "./docs/test-data/$name.txt"
      - uses: actions/cache@v2
        id: cache-save
        with:
          path: |
            ./docs/test-data/*
          key: multiple-files-${{ hashFiles('./docs/test-data/*') }}
  review:
    name: Review
    needs:
      - test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/cache@v2
        id: cache-restore
        with:
          path: |
            ./docs/test-data/*
          key: multiple-files-${{ hashFiles('./docs/test-data/*') }}
      - name: List
        run: |
          ls ./docs/test-data
