name: Workflow Matrix Reporter

on: ['push']

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: 'Alice'
          - name: 'Bob'
          - name: 'Eve'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Echo
        env:
          name: ${{matrix.name}}
        run: |
          date >> "./docs/test-data/$name.txt"
      - name: List
        run: |
          ls ./docs/test-data
  review:
    name: Review
    needs:
      - test
    runs-on: ubuntu-latest
    steps:
      - name: List
        run: |
          ls ./docs/test-data
