name: Authentication Tutorial

# Swith to on dispatch before merging.
# on:
#   workflow_dispatch:

on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - environment: 'dev'
            client_id: '${{ secrets.TRANSMUTE_STAGING_CLIENT_ID }}'
          - environment: 'test'
            client_id: 'token2'
    steps:
      - name: Echo site details
        env:
          environment: ${{secrets[matrix.environment]}}
          client_id: ${{secrets[matrix.client_id]}}
        run: echo $environment $client_id
# env:
#   CLIENT_ID: '${{ secrets.TRANSMUTE_STAGING_CLIENT_ID }}'
#   CLIENT_SECRET: '${{ secrets.TRANSMUTE_STAGING_CLIENT_SECRET }}'
#   TOKEN_AUDIENCE: '${{ secrets.TRANSMUTE_STAGING_TOKEN_AUDIENCE }}'
#   TOKEN_ENDPOINT: '${{ secrets.TRANSMUTE_STAGING_TOKEN_ENDPOINT }}'
#   API_BASE_URL: '${{ secrets.TRANSMUTE_STAGING_API_BASE_URL }}'

# jobs:
#   authentication-tutorial:
#     timeout-minutes: 5
#     runs-on: ubuntu-latest
#     steps:
#       - name: Begin CI...
#         uses: actions/checkout@v2

#       - name: Use Node 14
#         uses: actions/setup-node@v1
#         with:
#           node-version: 14.x

#       - name: Run Tests
#         run: |
#           npx newman run ./docs/tutorials/authentication-tutorial/authentication-tutorial.collection.json \
#           --env-var CLIENT_ID=${{ env.CLIENT_ID }} \
#           --env-var CLIENT_SECRET=${{ env.CLIENT_SECRET }} \
#           --env-var TOKEN_AUDIENCE=${{ env.TOKEN_AUDIENCE }} \
#           --env-var TOKEN_ENDPOINT=${{ env.TOKEN_ENDPOINT }} \
#           --env-var API_BASE_URL=${{ env.API_BASE_URL }} \
#           --reporters cli,json

#       # TODO: render the test suite report somewhere?
