name: Authentication Tutorial

# Swith to on dispatch before merging.
# on:
#   workflow_dispatch:

on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - environment: 'transmute staging'
            client_id: TRANSMUTE_STAGING_CLIENT_ID
            client_secret: TRANSMUTE_STAGING_CLIENT_SECRET
            token_audience: TRANSMUTE_STAGING_TOKEN_AUDIENCE
            token_endpoint: TRANSMUTE_STAGING_TOKEN_ENDPOINT
            api_base_url: TRANSMUTE_STAGING_API_BASE_URL

    steps:
      - name: Begin CI...
        uses: actions/checkout@v2
      - name: Use Node 14
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Run Tests
        env:
          client_id: ${{secrets[matrix.client_id]}}
          client_secret: ${{secrets[matrix.client_secret]}}
          token_audience: ${{secrets[matrix.token_audience]}}
          token_endpoint: ${{secrets[matrix.token_endpoint]}}
          api_base_url: ${{secrets[matrix.api_base_url]}}
        run: |
          npx newman run ./docs/tutorials/authentication-tutorial/authentication-tutorial.collection.json \
          --env-var CLIENT_ID=$client_id \
          --env-var CLIENT_SECRET=$client_secret \
          --env-var TOKEN_AUDIENCE=$token_audience \
          --env-var TOKEN_ENDPOINT=$token_endpoint \
          --env-var API_BASE_URL=$api_base_url \
          --reporters cli,json

# env:
#   CLIENT_ID: '${{ secrets.TRANSMUTE_STAGING_CLIENT_ID }}'
#   CLIENT_SECRET: '${{ secrets.TRANSMUTE_STAGING_CLIENT_SECRET }}'
#   TOKEN_AUDIENCE: '${{ secrets.TRANSMUTE_STAGING_TOKEN_AUDIENCE }}'
#   TOKEN_ENDPOINT: '${{ secrets.TRANSMUTE_STAGING_TOKEN_ENDPOINT }}'
#   API_BASE_URL: '${{ secrets.TRANSMUTE_STAGING_API_BASE_URL }}'

# jobs:
#   authentication-tutorial:
#     timeout-minutes: 5
#     runs-on: ubuntu-latest
#     steps:
#       - name: Begin CI...
#         uses: actions/checkout@v2

#       - name: Use Node 14
#         uses: actions/setup-node@v1
#         with:
#           node-version: 14.x

#       - name: Run Tests
#         run: |
#           npx newman run ./docs/tutorials/authentication-tutorial/authentication-tutorial.collection.json \
#           --env-var CLIENT_ID=${{ env.CLIENT_ID }} \
#           --env-var CLIENT_SECRET=${{ env.CLIENT_SECRET }} \
#           --env-var TOKEN_AUDIENCE=${{ env.TOKEN_AUDIENCE }} \
#           --env-var TOKEN_ENDPOINT=${{ env.TOKEN_ENDPOINT }} \
#           --env-var API_BASE_URL=${{ env.API_BASE_URL }} \
#           --reporters cli,json

#       # TODO: render the test suite report somewhere?
