name: Authentication Tutorial

# Swith to on dispatch before merging.
# on:
#   workflow_dispatch:

on: [push, pull_request]

env:
  TRANSMUTE_STAGING_CLIENT_ID: ${{ secrets.TRANSMUTE_STAGING_CLIENT_ID }}
  TRANSMUTE_STAGING_CLIENT_SECRET: ${{ secrets.TRANSMUTE_STAGING_CLIENT_SECRET }}
  TRANSMUTE_STAGING_TOKEN_AUDIENCE: ${{ secrets.TRANSMUTE_STAGING_TOKEN_AUDIENCE }}
  TRANSMUTE_STAGING_TOKEN_ENDPOINT: ${{ secrets.TRANSMUTE_STAGING_TOKEN_ENDPOINT }}
  TRANSMUTE_STAGING_API_BASE_URL: ${{ secrets.TRANSMUTE_STAGING_API_BASE_URL }}

jobs:
  authentication-tutorial:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - environment: 'Transmute Staging'
            CLIENT_ID: ${{ env.TRANSMUTE_STAGING_CLIENT_ID }}
            CLIENT_SECRET: ${{ env.TRANSMUTE_STAGING_CLIENT_SECRET }}
            TOKEN_AUDIENCE: ${{ env.TRANSMUTE_STAGING_TOKEN_AUDIENCE }}
            TOKEN_ENDPOINT: ${{ env.TRANSMUTE_STAGING_TOKEN_ENDPOINT }}
            API_BASE_URL: ${{ env.TRANSMUTE_STAGING_API_BASE_URL }}

    steps:
      - name: Begin CI...
        uses: actions/checkout@v2

      - name: Use Node 14
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Run Tests
        env:
          CLIENT_ID: ${{ matrix.CLIENT_ID }}
          CLIENT_SECRET: ${{ matrix.CLIENT_SECRET }}
          TOKEN_AUDIENCE: ${{ matrix.TOKEN_AUDIENCE }}
          TOKEN_ENDPOINT: ${{ matrix.TOKEN_ENDPOINT }}
          API_BASE_URL: ${{ matrix.API_BASE_URL }}
        run: |
          npx newman run ./docs/tutorials/authentication-tutorial/authentication-tutorial.collection.json \
          --env-var CLIENT_ID=$CLIENT_ID \
          --env-var CLIENT_SECRET=$CLIENT_SECRET \
          --env-var TOKEN_AUDIENCE=$TOKEN_AUDIENCE \
          --env-var TOKEN_ENDPOINT=TOKEN_ENDPOINT \
          --env-var API_BASE_URL=$API_BASE_URL \
          --reporters cli,json
