name: Update Conformance Schemas

on:
  workflow_dispatch:
  push:
    paths:
    - 'docs/openapi/**'

jobs:
  update-conformance-schemas:
    name: Update Conformance Schemas
    runs-on: ubuntu-latest
    steps:
      # Check out repo, set up node, and install dependencies.
      # @see https://github.com/actions/setup-node#usage
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.15.1
          cache: 'npm'
      - run: npm ci
      - name: Update Schemas
        working-directory: ./tests
        run: ./update_conformance_schemas.sh
      - name: Check for Updates
        id: update-check
        shell: bash {0} # Disable -eo pipefail
        working-directory: ./tests
        # Using `--exit-code` makes `git diff-index` exits with 1 if there
        # were differences and 0 if there were no differences.
        run: |
          git update-index --refresh conformance_suite.postman_collection.json
          git diff-index --exit-code HEAD
          echo "::set-output name=EXIT_CODE::$?"
      - name: Commit Updates
        if: ${{ steps.update-check.outputs.EXIT_CODE == 1 }}
        run: |
          git config --global user.name ${GITHUB_ACTOR}
          git config --global user.email ${GITHUB_ACTOR}@users.noreply.github.com
          git commit -am "bot: automated conformance schema updates"
          git push