name: Fixing 238

on:
  workflow_dispatch:

jobs:

  job1:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo Job 1
        exit 1

  job2:
    runs-on: ubuntu-latest
    needs: job1
    if: github.ref == 'refs/heads/main'
    steps:
      - run: echo job2

  job3:
    runs-on: ubuntu-latest
    needs: job1
    if: always()
    steps:
      - run: echo job3

  job4:
    runs-on: ubuntu-latest
    needs: job1
    if: always() && github.ref == 'xrefs/heads/main'
    steps:
      - run: echo job4

  job5:
    runs-on: ubuntu-latest
    needs: job1
    if: github.ref == 'xrefs/heads/main' && always()
    steps:
      - run: echo job5
