name: Interoperability Report

on:
  schedule:
    # Every day at midnight
    - cron: '0 0 * * *'
  workflow_dispatch:
  push:

jobs:

  sanity:
    name: Sanity
    runs-on: ubuntu-latest
    steps:
      # Check out repo, setup node, and install dependencies (cached).
      # @see https://github.com/actions/setup-node#usage
      # @see https://github.com/actions/cache/blob/main/examples.md#node---npm
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - uses: actions/cache@v3
        id: cache-npm
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      # Only install NPM packages if the `cache-npm` step misses.
      - run: npm ci
        if: steps.cache-npm.outputs.cache-hit != 'true'
      - name: Sanity Test
        run: |-
          npx newman run ./docs/tutorials/report-generation/report-tester.collection.json \
          --reporters cli,html,json \
          --reporter-html-export "${{format('sanity-{0}.html', github.job)}}" \
          --reporter-json-export "${{format('sanity-{0}.json', github.job)}}"
      - uses: actions/upload-artifact@v3
        with:
          name: sanity-report
          path: newman/

  credentials-issue:
    name: Issue Credential
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: "Mavennet"
            organization_did_web: MAVENNET_STAGING_ORGANIZATION_DID_WEB
            client_id: MAVENNET_STAGING_CLIENT_ID
            client_secret: MAVENNET_STAGING_CLIENT_SECRET
            token_audience: MAVENNET_STAGING_TOKEN_AUDIENCE
            token_endpoint: MAVENNET_STAGING_TOKEN_ENDPOINT
            api_base_url: MAVENNET_STAGING_API_BASE_URL
          - name: "mesur.io"
            organization_did_web: MESUR_IO_PRODUCTION_ORGANIZATION_DID_WEB
            client_id: MESUR_IO_PRODUCTION_CLIENT_ID
            client_secret: MESUR_IO_PRODUCTION_CLIENT_SECRET
            token_audience: MESUR_IO_PRODUCTION_TOKEN_AUDIENCE
            token_endpoint: MESUR_IO_PRODUCTION_TOKEN_ENDPOINT
            api_base_url: MESUR_IO_PRODUCTION_API_BASE_URL
          - name: "Transmute"
            organization_did_web: TRANSMUTE_STAGING_ORGANIZATION_DID_WEB
            client_id: TRANSMUTE_STAGING_CLIENT_ID
            client_secret: TRANSMUTE_STAGING_CLIENT_SECRET
            token_audience: TRANSMUTE_STAGING_TOKEN_AUDIENCE
            token_endpoint: TRANSMUTE_STAGING_TOKEN_ENDPOINT
            api_base_url: TRANSMUTE_STAGING_API_BASE_URL
    steps:
      # Check out repo, setup node, and install dependencies (cached).
      # @see https://github.com/actions/setup-node#usage
      # @see https://github.com/actions/cache/blob/main/examples.md#node---npm
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - uses: actions/cache@v3
        id: cache-npm
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      # Only install NPM packages if the `cache-npm` step misses.
      - run: npm ci
        if: steps.cache-npm.outputs.cache-hit != 'true'
      - name: Run Tests
        env:
          organization_did_web: ${{secrets[matrix.organization_did_web]}}
          client_id: ${{secrets[matrix.client_id]}}
          client_secret: ${{secrets[matrix.client_secret]}}
          token_audience: ${{secrets[matrix.token_audience]}}
          token_endpoint: ${{secrets[matrix.token_endpoint]}}
          api_base_url: ${{secrets[matrix.api_base_url]}}
        run: |
          npx newman run ./docs/tutorials/credentials-issue/credentials-issue.postman_collection.json \
          --env-var ORGANIZATION_DID_WEB=$organization_did_web \
          --env-var CLIENT_ID=$client_id \
          --env-var CLIENT_SECRET=$client_secret \
          --env-var TOKEN_AUDIENCE=$token_audience \
          --env-var TOKEN_ENDPOINT=$token_endpoint \
          --env-var API_BASE_URL=$api_base_url \
          --reporters cli,html,json \
          --reporter-html-export "${{format('credentials-issue-{0}-{1}.html', matrix.name, github.job)}}" \
          --reporter-json-export "${{format('credentials-issue-{0}-{1}.json', matrix.name, github.job)}}"
      - uses: actions/upload-artifact@v3
        with:
          name: credentials-issue
          path: newman/

  workflow-instance-join:
    name: Workflow Instance Join
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: "Transmute"
            org_1_token_endpoint: TRANSMUTE_PRODUCTION_TOKEN_ENDPOINT
            org_1_token_audience: TRANSMUTE_PRODUCTION_TOKEN_AUDIENCE
            org_1_api_base_url: TRANSMUTE_PRODUCTION_API_BASE_URL
            org_1_did_web: TRANSMUTE_PRODUCTION_TENANT_1_ORGANIZATION_DID_WEB
            org_1_client_id: TRANSMUTE_PRODUCTION_TENANT_1_CLIENT_ID
            org_1_client_secret: TRANSMUTE_PRODUCTION_TENANT_1_CLIENT_SECRET
            org_2_token_endpoint: TRANSMUTE_PRODUCTION_TOKEN_ENDPOINT
            org_2_token_audience: TRANSMUTE_PRODUCTION_TOKEN_AUDIENCE
            org_2_api_base_url: TRANSMUTE_PRODUCTION_API_BASE_URL
            org_2_did_web: TRANSMUTE_PRODUCTION_TENANT_2_ORGANIZATION_DID_WEB
            org_2_client_id: TRANSMUTE_PRODUCTION_TENANT_2_CLIENT_ID
            org_2_client_secret: TRANSMUTE_PRODUCTION_TENANT_2_CLIENT_SECRET
            org_3_token_endpoint: TRANSMUTE_PRODUCTION_TOKEN_ENDPOINT
            org_3_token_audience: TRANSMUTE_PRODUCTION_TOKEN_AUDIENCE
            org_3_api_base_url: TRANSMUTE_PRODUCTION_API_BASE_URL
            org_3_did_web: TRANSMUTE_PRODUCTION_TENANT_3_ORGANIZATION_DID_WEB
            org_3_client_id: TRANSMUTE_PRODUCTION_TENANT_3_CLIENT_ID
            org_3_client_secret: TRANSMUTE_PRODUCTION_TENANT_3_CLIENT_SECRET
    steps:
      # Check out repo, setup node, and install dependencies (cached).
      # @see https://github.com/actions/setup-node#usage
      # @see https://github.com/actions/cache/blob/main/examples.md#node---npm
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - uses: actions/cache@v3
        id: cache-npm
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      # Only install NPM packages if the `cache-npm` step misses.
      - run: npm ci
        if: steps.cache-npm.outputs.cache-hit != 'true'
      - name: Workflow Instance Join
        env:
          org_1_token_endpoint: ${{secrets[matrix.org_1_token_endpoint]}}
          org_1_token_audience: ${{secrets[matrix.org_1_token_audience]}}
          org_1_api_base_url: ${{secrets[matrix.org_1_api_base_url]}}
          org_1_did_web: ${{secrets[matrix.org_1_did_web]}}
          org_1_client_id: ${{secrets[matrix.org_1_client_id]}}
          org_1_client_secret: ${{secrets[matrix.org_1_client_secret]}}
          org_2_token_endpoint: ${{secrets[matrix.org_2_token_endpoint]}}
          org_2_token_audience: ${{secrets[matrix.org_2_token_audience]}}
          org_2_api_base_url: ${{secrets[matrix.org_2_api_base_url]}}
          org_2_did_web: ${{secrets[matrix.org_2_did_web]}}
          org_2_client_id: ${{secrets[matrix.org_2_client_id]}}
          org_2_client_secret: ${{secrets[matrix.org_2_client_secret]}}
          org_3_token_endpoint: ${{secrets[matrix.org_3_token_endpoint]}}
          org_3_token_audience: ${{secrets[matrix.org_3_token_audience]}}
          org_3_api_base_url: ${{secrets[matrix.org_3_api_base_url]}}
          org_3_did_web: ${{secrets[matrix.org_3_did_web]}}
          org_3_client_id: ${{secrets[matrix.org_3_client_id]}}
          org_3_client_secret: ${{secrets[matrix.org_3_client_secret]}}
        run: |
          npx newman run ./docs/tutorials/workflow-join/ecommerce-workflow-instance-join.collection.json \
          --env-var ORG_1_TOKEN_ENDPOINT=$org_1_token_endpoint \
          --env-var ORG_1_TOKEN_AUDIENCE=$org_1_token_audience \
          --env-var ORG_1_BASE_URL=$org_1_api_base_url \
          --env-var ORG_1_DID_WEB=$org_1_did_web \
          --env-var ORG_1_CLIENT_ID=$org_1_client_id \
          --env-var ORG_1_CLIENT_SECRET=$org_1_client_secret \
          --env-var ORG_2_TOKEN_ENDPOINT=$org_2_token_endpoint \
          --env-var ORG_2_TOKEN_AUDIENCE=$org_2_token_audience \
          --env-var ORG_2_BASE_URL=$org_2_api_base_url \
          --env-var ORG_2_DID_WEB=$org_2_did_web \
          --env-var ORG_2_CLIENT_ID=$org_2_client_id \
          --env-var ORG_2_CLIENT_SECRET=$org_2_client_secret \
          --env-var ORG_3_TOKEN_ENDPOINT=$org_3_token_endpoint \
          --env-var ORG_3_TOKEN_AUDIENCE=$org_3_token_audience \
          --env-var ORG_3_BASE_URL=$org_3_api_base_url \
          --env-var ORG_3_DID_WEB=$org_3_did_web \
          --env-var ORG_3_CLIENT_ID=$org_3_client_id \
          --env-var ORG_3_CLIENT_SECRET=$org_3_client_secret \
          --reporters cli,html,json \
          --reporter-html-export "${{format('workflow-instance-join-{0}-{1}.html', matrix.name, github.job)}}" \
          --reporter-json-export "${{format('workflow-instance-join-{0}-{1}.json', matrix.name, github.job)}}"
      - uses: actions/upload-artifact@v3
        with:
          name: workflow-instance-join
          path: newman/

  publish:
    name: Publish
    runs-on: ubuntu-latest

    # Always run, regardless of whether jobs that this one depends on have
    # succeeded or failed.
    if: ${{ always() }}

    # All jobs for which output will be published must be complete before this
    # job can run.
    needs:
      - sanity
      - credentials-issue
      - workflow-instance-join

    steps:
      # Check out repo, setup node, and install dependencies (cached).
      # @see https://github.com/actions/setup-node#usage
      # @see https://github.com/actions/cache/blob/main/examples.md#node---npm
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - uses: actions/cache@v3
        id: cache-npm
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      # Only install NPM packages if the `cache-npm` step misses.
      - run: npm ci
        if: steps.cache-npm.outputs.cache-hit != 'true'

      # Download Artifacts
      #
      # Each of the report artifacts created in previous steps should be
      # downloaded here so that the report preparation code can ingest the
      # raw newman output and generate sanitized reports for publishing.

      - uses: actions/download-artifact@v3
        with:
          name: sanity-report
          path: newman/
      - uses: actions/download-artifact@v3
        with:
          name: credentials-issue
          path: newman/
      - uses: actions/download-artifact@v3
        with:
          name: workflow-instance-join
          path: newman/

      # Remove this after confirming that downloaded artifacts do not trample
      # each other.
      - name: Debug output
        run: ls -R ./newman

      # Sanitize newman output, generate report index, and write all otuput to
      # the `./docs/reports` folder for publishing.
      - name: Rebuilding index
        run: npm run report:prepare

      # Build the JSON version of the OpenAPI specification from the YAML source
      # files prior to publishing.
      - name: Build Open API Specification JSON
        run: npm run preserve

      - name: Publish Reports
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
