name: Interoperability Report

on:
  schedule:
    # Every day at midnight
    - cron: '0 0 * * *'
  workflow_dispatch:
  push:

jobs:

  interop-sanity:
    name: Sanity
    runs-on: ubuntu-latest
    steps:
      # Check out repo, setup node, and install dependencies.
      # @see https://github.com/actions/setup-node#usage
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'npm'
      - run: npm ci
      - name: Sanity Test
        run: |-
          npx newman run ./docs/tutorials/report-generation/report-tester.collection.json \
          --reporters cli,html,json \
          --reporter-html-export "newman/${{format('{0}-{1}.html', github.run_id, github.job)}}" \
          --reporter-json-export "newman/${{format('{0}-{1}.json', github.run_id, github.job)}}"
      # Sanitize newman output and write all reports to the `./docs/reports`
      # folder for publishing, excluding `index.html`, which will be rebuilt
      # during publishing.
      - name: Sanitize Newman Output
        if: ${{ always() }} # Run even when postman tests fail
        run: |
          npm run report:prepare
          rm -f ./docs/reports/index.html
      - uses: actions/upload-artifact@v3
        if: ${{ always() }} # Run even when postman tests fail
        with:
          name: sanity-report
          path: docs/reports/

  interop-credentials-issue:
    name: Unit
    uses: ./.github/workflows/regression-credentials-issue.yml

  interop-credentials-verify:
    name: Unit
    uses: ./.github/workflows/regression-credentials-verify.yml

  interop-did-web-discovery:
    name: Unit
    uses: ./.github/workflows/regression-did-web-discovery.yml

  interop-presentations-exchange:
    name: Unit
    uses: ./.github/workflows/regression-presentations-exchange.yml

  interop-presentations-verify:
    name: Unit
    uses: ./.github/workflows/regression-presentations-verify.yml

  interop-workflow-instance-join:
    name: Unit
    uses: ./.github/workflows/regression-workflow-instance-join.yml

  interop-publish:
    name: Publish
    runs-on: ubuntu-latest

    # Always run, regardless of whether jobs that this one depends on have
    # succeeded or failed.
    if: ${{ always() }}

    # All jobs for which output will be published must be complete before this
    # job can run.
    needs:
      - interop-sanity
      - interop-credentials-issue
      - interop-credentials-verify
      - interop-did-web-discovery
      - interop-presentations-exchange
      - interop-presentations-verify
      - interop-workflow-instance-join

    steps:
      # Check out repo, setup node, and install dependencies.
      # @see https://github.com/actions/setup-node#usage
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'npm'
      - run: npm ci

      # Download Artifacts
      #
      # Each of the report artifacts created in previous steps should be
      # aggregated before building the report index.

      - uses: actions/download-artifact@v3
        with:
          name: sanity-report
          path: docs/reports/
      - uses: actions/download-artifact@v3
        with:
          name: credentials-issue
          path: docs/reports/
      - uses: actions/download-artifact@v3
        with:
          name: credentials-verify
          path: docs/reports/
      - uses: actions/download-artifact@v3
        with:
          name: did-web-discovery
          path: docs/reports/
      - uses: actions/download-artifact@v3
        with:
          name: presentations-exchange
          path: docs/reports/
      - uses: actions/download-artifact@v3
        with:
          name: presentations-verify
          path: docs/reports/
      - uses: actions/download-artifact@v3
        with:
          name: workflow-instance-join
          path: docs/reports/

      # Build reports index prior to publishing
      - name: Build reports index
        run: npm run report:prepare

      # Build the JSON version of the OpenAPI specification from the YAML source
      # files prior to publishing.
      - name: Build Open API Specification JSON
        run: npm run preserve

      - name: Publish Reports
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
