name: Minimum Fail

on:
  workflow_dispatch:
  push:
    branches:
    - "fix/newman-json-output"

jobs:
  minimum-fail:
    name: Minimum Fail
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: "mesur.io"
            actor: "MESUR_IO_PRODUCTION"
    steps:
      # Check out repo, setup node, and install dependencies.
      # @see https://github.com/actions/setup-node#usage
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'npm'
      - run: npm ci
      - name: Run Tests
        run: |
          npx newman run ./docs/tutorials/minimum-fail/minimum-fail.postman_collection.json \
          --reporters cli,htmlextra,json \
          --reporter-htmlextra-skipSensitiveData \
          --reporter-htmlextra-export "newman/${{format('{0}-{1}-{2}.html', github.run_id, github.job, matrix.name)}}" \
          --reporter-json-export "newman/${{format('{0}-{1}-{2}.json', github.run_id, github.job, matrix.name)}}"
      - uses: actions/upload-artifact@v3
        if: ${{ always() }} # Run even when postman tests fail
        with:
          name: presentations-verify
          path: newman/
