name: OpenAPI

on:
  push:
    branches:
    - main
    paths:
    - 'docs/openapi/**'

jobs:
  openapi-build:
    runs-on: ubuntu-latest
    steps:

      # Check out repo, setup node, and install dependencies.
      # @see https://github.com/actions/setup-node#usage
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.15.1
          cache: 'npm'
      - run: npm ci

      # Build the JSON version of the OpenAPI specification from the YAML source
      # files prior to publishing.
      - name: Build Open API Specification JSON
        run: npm run preserve

      # Publish openapi subfolder to GitHub Pages
      - name: Publish Open API Specification
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/openapi
          destination_dir: openapi

