name: Publish Report Index

on:
  push:
    branches:
    - main
    paths:
    - 'docs/reports/archive/**'

jobs:
  publish-index:
    runs-on: ubuntu-latest
    steps:

      # Check out repo, setup node, and install dependencies.
      # @see https://github.com/actions/setup-node#usage
      - uses: actions/checkout@v3

      # Publish reports/archive subfolder to GitHub Pages
      - name: Publish Open API Specification
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/reports/archive
          destination_dir: reports/archive
