name: Publish Reports

on:
  workflow_dispatch:

jobs:

  # collect-artifacts collects newman report output artifacts from various
  # reporting jobs for use in other jobs in this workflow.
  collect-artifacts:
    name: Collect Artifacts
    runs-on: ubuntu-latest

    steps:
      # Check out repo, setup node, and install dependencies.
      # @see https://github.com/actions/setup-node#usage
      - uses: actions/checkout@v3

      # Download Artifacts
      #
      # Each of the report artifacts created in previous steps should be
      # aggregated before building the report index.

      - uses: actions/download-artifact@v3
        with:
          name: sanity-report
          path: docs/reports/

      - uses: actions/download-artifact@v3
        with:
          name: credentials-issue
          path: docs/reports/

      - uses: actions/download-artifact@v3
        with:
          name: credentials-verify
          path: docs/reports/

      - uses: actions/download-artifact@v3
        with:
          name: credentials-revocation
          path: docs/reports/

      - uses: actions/download-artifact@v3
        with:
          name: did-web-discovery
          path: docs/reports/

      - uses: actions/download-artifact@v3
        with:
          name: presentations-exchange
          path: docs/reports/

      - uses: actions/download-artifact@v3
        with:
          name: presentations-verify
          path: docs/reports/

      - uses: actions/download-artifact@v3
        with:
          name: workflow-instance-join
          path: docs/reports/

      # Create artifact containing collected raw reporting output
      - uses: actions/upload-artifact@v3
        with:
          name: raw-report-artifacts
          path: docs/reports/

  # build-reports uses previously collected raw reporting artifacts to build
  # consumable reports.
  build-reports:
    name: Build Reports
    runs-on: ubuntu-latest

    # artifacts must be collected before reports can be built
    needs: collect-artifacts

    steps:
      # Check out repo, setup node, and install dependencies.
      # @see https://github.com/actions/setup-node#usage
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'npm'
      - run: npm ci

      # Set up Python 3.9
      - name: Set up Pyton 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install Python Dependencies
        run: |
          # $CONDA points to the root of the miniconda directory
          $CONDA/bin/conda env update --file reporting/environment.yml --name base

      # Build report index
      - name: Build JSON Index
        run: npm run report:prepare

      # Build interactive report
      - name: Build Interactive Report
        working-directory: ./reporting
        run: ./reporter.py --mode ci

      # Publish reports subfolder to GitHub Pages
      - name: Publish Reports
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/reports
          destination_dir: reports

