name: Publish Editor's Draft

on:
  push:
    branches:
    - main
    paths:
    - 'docs/spec/**'

jobs:
  publish-editors-draft:
    runs-on: ubuntu-latest
    steps:

      # Check out repo, setup node, and install dependencies.
      # @see https://github.com/actions/setup-node#usage
      - uses: actions/checkout@v3

      # Publish editor's draft to GitHub Pages
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/spec
          destination_dir: draft
