name: Credentials Issue

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      # See matrix of secrets...
      # https://sbulav.github.io/terraform/github-actions-matrix-secrets/
      matrix:
        include:
          - organization_did_web: MESUR_IO_PRODUCTION_ORGANIZATION_DID_WEB
            client_id: MESUR_IO_PRODUCTION_CLIENT_ID
            client_secret: MESUR_IO_PRODUCTION_CLIENT_SECRET
            token_audience: MESUR_IO_PRODUCTION_TOKEN_AUDIENCE
            token_endpoint: MESUR_IO_PRODUCTION_TOKEN_ENDPOINT
            api_base_url: MESUR_IO_PRODUCTION_API_BASE_URL
          - organization_did_web: TRANSMUTE_STAGING_ORGANIZATION_DID_WEB
            client_id: TRANSMUTE_STAGING_CLIENT_ID
            client_secret: TRANSMUTE_STAGING_CLIENT_SECRET
            token_audience: TRANSMUTE_STAGING_TOKEN_AUDIENCE
            token_endpoint: TRANSMUTE_STAGING_TOKEN_ENDPOINT
            api_base_url: TRANSMUTE_STAGING_API_BASE_URL

    steps:
      - name: Check out git repository
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: Run Tests
        env:
          organization_did_web: ${{secrets[matrix.organization_did_web]}}
          client_id: ${{secrets[matrix.client_id]}}
          client_secret: ${{secrets[matrix.client_secret]}}
          token_audience: ${{secrets[matrix.token_audience]}}
          token_endpoint: ${{secrets[matrix.token_endpoint]}}
          api_base_url: ${{secrets[matrix.api_base_url]}}
        run: |
          npx newman run ./docs/tutorials/credentials-issue/credentials-issue.postman_collection.json \
          --env-var ORGANIZATION_DID_WEB=$organization_did_web \
          --env-var CLIENT_ID=$client_id \
          --env-var CLIENT_SECRET=$client_secret \
          --env-var TOKEN_AUDIENCE=$token_audience \
          --env-var TOKEN_ENDPOINT=$token_endpoint \
          --env-var API_BASE_URL=$api_base_url \
          --reporters cli,json
