name: TEST Interoperability Report

on:
  push:
  workflow_dispatch:

jobs:

  interop-presentations-exchange:
    name: Presentations Exchange
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: "mesur.io-Transmute"
            issuer: MESUR_PRODUCTION
            verifier: TRANSMUTE_STAGING
    steps:
      # Check out repo, setup node, and install dependencies.
      # @see https://github.com/actions/setup-node#usage
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'npm'
      - run: npm ci
      - name: Run Tests
        env:
          issuer_token_endpoint: ${{secrets[format('MESUR_PRODUCTION_TOKEN_ENDPOINT')]}}
          verifier_token_endpoint: ${{secrets[format('TRANSMUTE_STAGING_TOKEN_ENDPOINT')]}}
        run: |
          env | grep token
          echo ${{format('{0}_TOKEN_ENDPOINT', matrix.issuer)}}
          echo $issuer_token_endpoint
